### ISSUE TITLE
Problems with leaving initialRoute unset…

### ISSUE THREAD

**Issue by hedefalk** [jesse1983/marko-router5#2]
Sorry to post as a bug as this is rather a question. Maybe noob question at that :)

Anyway, I'm trying to use this with Marko served via webpack-serve. So I use this koa2-connect-history-api-fallback middleware to always go to my index.html to init the router.

What I have is something simple like:

```
$ const routes = [
  { name: 'home', path: '/', component: require('./pages/home.marko') },
  { name: 'faq', path: '/faq', component: require('./pages/faq.marko') },
  { name: 'help', path: '/help', component: require('./pages/help.marko') },
]

router routes=routes  options={ defaultRoute: 'home', initialRoute: 'home' }
```

So just navigating to my site I always get to / now because of that middleware. So if I output a link with `<route-link href="/help">Hjälp</route-link>` that works fine and clicking it the right marko component is loaded and the browser navbar is updated to '/help' correctly. However, hitting refresh here I'm redirected to '/' again and not being deep-linked which I intend. 

I guess I'm missing a piece of the puzzle here with how to setup the initial/default route when the router is initiated. Should I manually parse the request string when initializing the router and put that in initialRoute possibly? Do you have an example of deep linking?

**Comment by hedefalk** [comment]
Actually window.location.pathname is '/' when I arrive at my init of the router:

![image](https://user-images.githubusercontent.com/116520/43966252-acfee486-9cc1-11e8-98a8-c34184b13413.png)

```
$ console.log(window.location)
router routes=routes  options={ defaultRoute: 'home', initialRoute: 'home' }
```

So I guess I need to do something smarter than that to get the requests original path to use for the router?

**Comment by hedefalk** [comment]
Oh, sorry, I was wrong. This seem to work fine:

router routes=routes  options={ defaultRoute: 'home', initialRoute: window.location.pathname }

**Comment by hedefalk** [comment]
Actually, I really think there needs to be some explanation of option.initialRoute. Setting nothing results in js error and it isn't documented under https://jesse1983.github.io/marko-router5/#/?id=router-options and not part of router5's options as far as I can tell.

What I find is this:

https://github.com/jesse1983/marko-router5/blob/d06bdea4f9a33347b32ac54fa9ba13e2d4fcbba2/src/components/router/component.js#L27

As I understand it initialRoute is what should be used and defaultRoute is just if nothing else is matched. So in my case

`router routes=routes options={ defaultRoute: 'home', initialRoute: window.location.pathname }`

is perfect, but the documentation is lacking here.

**Comment by jesse1983** [comment]
Hi @hedefalk 
Thanks for help.

I changed `options.initialRoute` to `initialPath` attribute [https://jesse1983.github.io/marko-router5/#/?id=initialpath](https://jesse1983.github.io/marko-router5/#/?id=initialpath):

```xml
<router routes=routes initial-path="/home" />
``` 

Options attribute is only for Router5 Options.

Can you see if that fix the problem?

**Comment by hedefalk** [comment]
@jesse1983 Works like a charm with:
