### ISSUE TITLE
placeholder div is disruptive for css

### ISSUE THREAD

**Issue by hedefalk** [jesse1983/marko-router5#3]
The placeholder div:

https://github.com/jesse1983/marko-router5/blob/7d4bfc2fd21c04e5d585bcae6a9a76574a695ed3/src/components/router/index.marko#L1

is a bit disruptive in a case like mine where I really need better control over the html. I want header, main and footer straight on body:

![image](https://user-images.githubusercontent.com/116520/44582342-9e2b2100-a7a1-11e8-8248-0026a40b0f3b.png)

I can't find any references to it more than the router component so I'm wondering if it's just fine to ditch it?

**Comment by hedefalk** [comment]
I had some problems first to override just the markup in a marko component but in the end it worked by just sticking the markup in a .marko file:

```
<if(state.renderBody)>
  <include(state.renderBody) ...state.inputs />
</if>
```

And component.js:

```
// Ugly hack to patch marko5-router without surrounding div
const router = require('marko-router5/src/components/router/component')
module.exports = router
```

This works fine for me but I'd much rather PR upstream here :) Any reason not to remove the div?

**Comment by jesse1983** [comment]
Hi @hedefalk ,

Can you try version 1.0.5? I created a new attribute `no-wrapper` no remove this div.

https://github.com/jesse1983/marko-router5#nowrapper

**Comment by hedefalk** [comment]
Works fine, thanks!
